---
- hosts: localhost
  gather_facts: true
  tasks:
   - name: Recursively find logs files older than 10 days
     find:
        paths: "/home/ansadmin/logs"
        age: 0d
        recurse: yes
     register: logfiles
   - debug: var=logfiles
   - name: copy those output files into localmachine
     copy:
        src: "{{ item.path }}"
        dest: /home/ansadmin/folder/
        owner: ansadmin
        group: ansadmin
        mode: 0644
        backup: yes
     become: true
     become_method: sudo
     with_items:
      - "{{ logfiles.files }}"
   - name: Put logs in S3 bucket which is more than 10 days
     aws_s3:
        bucket: ci-proj
        mode: put
        src: "{{ item.path }}"
        object: "/logs/newone/{{ item.path }}"
     become: true
     become_method: sudo
     with_items: "{{ logfiles.files }}"
#     with_items: "{{ logfiles.files }}"
     tags: cp
